logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
    sender:
      type: web
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:8080/api-o/user-me
      prefer-token-info: false